name: Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
      - name: Download JBR
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.10-osx-aarch64-b1171.14.tar.gz'
          file-name: 'jbr-17.0.10.tar.gz'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: jdkfile
          jdkFile: jbr-17.0.10.tar.gz
          cache: gradle

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA_MACOS }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD_MACOS }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :composeApp:packageReleaseDmg

      - name: Match
        run: bundle exec fastlane match developer_id --username $APPSTORE_USERNAME --git_url $CERTS_REPO --git_basic_authorization $GIT_AUTH --git_branch info --skip_certificate_matching true --readonly --team_id $APPSTORE_TEAMIDENTIFIER --app_identifier --gitlab_host $GITLAB_HOST,
        env:
          APPSTORE_TEAMIDENTIFIER: ${{ secrets.APPSTORE_TEAMIDENTIFIER }}
          APPSTORE_USERNAME: ${{ secrets.APPSTORE_USERNAME }}
          CERTS_REPO: ${{ secrets.CERTS_REPO }}
          GIT_AUTH: ${{ secrets.GIT_AUTH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GITLAB_HOST: ${{ secrets.GITLAB_HOST }}

      - name: Upload DMG as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Toggl2Float-dmg
          path: composeApp/build/compose/binaries/main-release/dmg/*.dmg

  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JBR
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.7-windows-x64-b1000.2.tar.gz'
          file-name: 'jbr-17.0.7.tar.gz'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: jdkfile
          jdkFile: jbr-17.0.7.tar.gz
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew.bat :composeApp:packageReleaseExe

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Toggl2Float-exe
          path: composeApp/build/compose/binaries/main-release/exe/*.exe
