name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download JBR
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.7-osx-aarch64-b1000.2.tar.gz'
          file-name: 'jbr-17.0.7.tar.gz'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: jdkfile
          jdkFile: jbr-17.0.7.tar.gz
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew packageReleaseDmg

      - name: Upload DMG as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Toggl2Float-dmg
          path: build/compose/binaries/main-release/dmg/*.dmg

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/compose/binaries/main-release/dmg/*.dmg
